### ISSUE TITLE
Distribution graded UNKNOWN during automated testing

### ISSUE THREAD

**Issue by jkeenan** [bluefeet/Test-Starch#1]
As part of preparation for the upcoming release of perl-5.30.0, I attempted to build and install Test-Starch today on FreeBSD-11.2 using ```cpanm``` as the installer as part of my larger "test the CPAN River 3000 against dev" program.  'cpanm' graded the distribution ```UNKNOWN```. 
```
$ ~/bin/perl/dumpjson BLUEFEET.Test-Starch-0.12.log.json |less
{
  author => "BLUEFEET",
  dist => "Test-Starch",
  distname => "Test-Starch-0.12",
  distversion => 0.12,
  grade => "UNKNOWN",
  prereqs => undef,
  test_output => [
    "Building and testing Test-Starch-0.12",
    "cp lib/Test/Starch.pm blib/lib/Test/Starch.pm",
    "t/basic.t .. skipped: Module 'Starch' is not installed",
    "Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.08 cusr  0.09 csys =  0.19 CPU)",
    "Result: NOTESTS",
  ],
  via => "App::cpanminus::reporter 0.17 (1.7044)",
}
```
However, when I ran ```./Build test```, the test suite was graded ```PASS```.

Here is a possible explanation of this anomaly.

My CPAN-River testing program, run once a month after a new dev release, attempts to install distributions in dependency order.  If a given distribution has **new** dependencies in a given month, the program attempts to install those dependencies, which means they show up in the monthly CPAN river report even if they were not specified in the "CPAN River 3000" list (which is compiled once a year after a Perl production release).

It appears that Test-Starch had a new version uploaded to CPAN within the past 30 days.  Its ```META.yml``` file lists the Starch distribution as **recommended** -- but not as **required**.  Hence, it is likely that when Test-Starch was encountered during my program, the Starch distribution had not already been installed and that, since it was merely recommended as a prerequisite for Test-Starch rather than as a requirement, Test-Starch was neither built nor tested.  This would explain the ```UNKNOWN``` and the ```NOTESTS``` reported above.

This would also explain similar results in this and other CPANtesters runs: 
http://www.cpantesters.org/cpan/report/0d55fd2c-3bed-11e9-b1af-bcbc36887cd3;
(from http://matrix.cpantesters.org/?dist=Test-Starch%200.12;os=linux;perl=5.29.8;reports=1).  If the CPANtester contributor (Slaven -- who is the best there is at this) were testing on a given Linux box for the first time and testing distros in dependency order, then he might encounter Test-Starch before Starch itself had been installed.  Since Test-Starch does not absolutely require Starch, testing for Test-Starch would be graded ```UNKNOWN```.  His program would then proceed to install Starch -- which means that if he re-tested Test-Starch on the same box at a later date, it would now ```PASS```.

So, I think you should make Starch a hard requirement for Test-Starch -- not just a recommendation.

Thank you very much.
Jim Keenan

**Comment by bluefeet** [comment]
Eh, ya, I moved Test::Starch into its own Test-Starch distro and it was a bad decision.  I've just released Starch 0.13 which includes Test::Starch once again: bluefeet/Starch@6f7306059e748904287941222e8002b6138629e8
